module-title = "Google Cloud SDK"

input-descriptor-file = "sable-test.pb"

output-dir = "output"

enable-lunr-search = true

main-page-content-file = "intro.md"

footer-content = "Â© Example 2023"

repository-url = "https://github.com/googleapis/googleapis"
repository-type = "github"
repository-branch = "master"
